services:
  - type: web
    name: backend-django
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
     - key: DJANGO_SETTINGS_MODULE
      value: backend.settings


    
